name: Build Kext

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Bước checkout mã nguồn
      - name: Checkout source code
        uses: actions/checkout@v4

      # Cài đặt dependencies (nếu cần)
      - name: Install Dependencies
        run: |
          brew update
          brew install cmake # Nếu dùng cmake, thêm các công cụ cần thiết

      # Build Kext
      - name: Build Kext
        run: |
          xcodebuild -project MyKext.xcodeproj \
            -scheme MyKext \
            -sdk macosx \
            -configuration Release \
            build

      # Upload artifact (tùy chọn)
      - name: Upload Built Kext
        uses: actions/upload-artifact@v4
        with:
         
